apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: jineshnagori/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 8080
    targetPort: 5000